name: sv-nf
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - bcftools=1.9
  - samtools=1.9
  - bedtools=2.29.2
  - r-data.table
  - r-dplyr
  - r-glue
  - r-maditr
  - r-magrittr
  - r-gsheet
  - r-stringr